### ISSUE TITLE
ImportError: No module named 'utils.prepare'; 'utils' is not a package

### ISSUE THREAD

**Issue by OmriKaduri** [eragonruan/text-detection-ctpn#308]
In `split_label.py` file, you have a broken import to functions from `utils.prepare.utils`.

Try change this:
```python
from utils import orderConvex, shrink_poly
```

**Comment by wangjiaod** [comment]
您好，请问您用split_label生成的img_859.jpg的标签文件与源码中给的img_859.txt一样吗？

**Comment by Doloresru** [comment]
I fix the problem with your solution,but when processing image ,it is error.Do you have meet the same problem?

**Comment by Doloresru** [comment]
> 您好，请问您用split_label生成的img_859.jpg的标签文件与源码中给的img_859.txt一样吗？

hi ,what problem do you met?I output two empty fold

**Comment by cellphonef** [comment]
> I fix the problem with your solution,but when processing image ,it is error.Do you have meet the same problem?

I met the same problem as you. how do you solve you?

**Comment by wangjiaod** [comment]
Thanks very much!I try again .------------------ 原始邮件 ------------------
发件人: "cellphonef"<notifications@github.com>
发送时间: 2019年5月7日(星期二) 晚上7:28
收件人: "eragonruan/text-detection-ctpn"<text-detection-ctpn@noreply.github.com>;
抄送: "wangjiaod"<1412015254@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [eragonruan/text-detection-ctpn] ImportError: No module named'utils.prepare'; 'utils' is not a package (#308)


 
I fix the problem with your solution,but when processing image ,it is error.Do you have meet the same problem?
  
I met the same problem as you. how do you solve you?
 
&mdash;

**Comment by Doan-Nguyen** [comment]
I fixed problem when change: 
"from utils.prepare.utils import orderConvex, shrink_poly"
to "from utils import orderConvex, shrink_poly"

**Comment by yzq-123** [comment]
@Doan-Nguyen It seems that the problem is still not solved.Can you speak clearly?

**Comment by ShaominLi** [comment]
modify split_label.py
![image](https://user-images.githubusercontent.com/18107588/69855885-75a8a580-12c7-11ea-8771-1470486fab0b.png)

**Comment by ShaominLi** [comment]
modify the split_label.py
`sys.path.append(os.path.join(os.getcwd(), 'utils/prepare'))
 from utils import orderConvex, shrink_poly`

**Comment by ShaominLi** [comment]
modify the split_label.py:
`sys.path.append(os.path.join(os.getcwd(), 'utils/prepare'))`
`from utils import orderConvex, shrink_poly`

**Comment by Doan-Nguyen** [comment]
> @Doan-Nguyen It seems that the problem is still not solved.Can you speak clearly?

Hi @yzq-123, so sorry because reply so late. You can check my gist here. 
https://gist.github.com/Doan-Nguyen/bb022dab02a8c875ebb7cc313449f7e6
